[project]
name = "monarch-money-mcp"
version = "0.2.1"
description = "MCP server for MonarchMoney financial data access"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.9.4",
    "monarchmoney-enhanced",
]

[project.scripts]
monarch-money-mcp = "server:main"
